version: '3.1'

services:
  db:
    image: mariadb:10.5
    container_name: maindb
    environment:
      MYSQL_ROOT_PASSWORD: 54fghjghjk44RkjJHkhgv3798

  main:
    build: .
    container_name: main
    links:
      - db:maindb
